<a href="https://colab.research.google.com/github/raufur-simanto/Generative-AI/blob/main/text_representation_with_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Bag of words


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [ ]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [ ]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [ ]:
X = bow.toarray()
y = df['output']

### N-grams

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:

# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [ ]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]


## TF-IDF (Term frequency- Inverse document frequency)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [ ]:
arr = tfid.fit_transform(df['text']).toarray()

In [ ]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

## Word2Vec

In [ ]:
!pip install --upgrade gensim --user

In [ ]:
import numpy as np
import pandas as pd
import gensim
import os

In [ ]:

from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
## download the got dataset
import kagglehub

# Download latest version
path = kagglehub.dataset_download("khulasasndh/game-of-thrones-books")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'game-of-thrones-books' dataset.
Path to dataset files: /kaggle/input/game-of-thrones-books


In [ ]:
data = path

In [ ]:
print(data)

/kaggle/input/game-of-thrones-books


In [ ]:
## file path
files = os.listdir(data)
files
# first_book = os.path.join(path,'004ssb.txt')

['004ssb.txt', '005ssb.txt', '001ssb.txt', '002ssb.txt', '003ssb.txt']

In [ ]:
new_path = os.path.join(path,'004ssb.txt')

In [ ]:
story = []
f = open(os.path.join(path,'004ssb.txt'), encoding='cp1252')
corpus = f.read()
raw_sent = sent_tokenize(corpus)
for sent in raw_sent:
  story.append(simple_preprocess(sent))

In [ ]:
story

[['version',
  'history',
  'reedited',
  'by',
  'maelstrom',
  'feast',
  'for',
  'crows',
  'book',
  'four',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'george'],
 ['martin', 'prologue', 'dragons', 'said', 'mollander'],
 ['he',
  'snatched',
  'withered',
  'apple',
  'off',
  'the',
  'ground',
  'and',
  'tossed',
  'it',
  'hand',
  'to',
  'hand'],
 ['throw', 'the', 'apple', 'urged', 'alleras', 'the', 'sphinx'],
 ['he',
  'slipped',
  'an',
  'arrow',
  'from',
  'his',
  'quiver',
  'and',
  'nocked',
  'it',
  'to',
  'his',
  'bowstring'],
 ['should',
  'like',
  'to',
  'see',
  'dragon',
  'roone',
  'was',
  'the',
  'youngest',
  'of',
  'them',
  'chunky',
  'boy',
  'still',
  'two',
  'years',
  'shy',
  'of',
  'manhood'],
 ['should',
  'like',
  'that',
  'very',
  'much',
  'and',
  'should',
  'like',
  'to',
  'sleep',
  'with',
  'rosey',
  'arms',
  'around',
  'me',
  'pate',
  'thought'],
 ['he', 'shifted', 'restlessly', 'on', 'the', 'bench'],
 ['by', '

In [ ]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [ ]:
model.build_vocab(story)

In [ ]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(1131678, 1517045)

In [ ]:
model.wv.most_similar('daenerys')

[('feed', 0.9842978715896606),
 ('until', 0.9841184616088867),
 ('stands', 0.9840342402458191),
 ('next', 0.9838513731956482),
 ('stranger', 0.9834840297698975),
 ('catch', 0.9826041460037231),
 ('god', 0.9825559854507446),
 ('listening', 0.9824506044387817),
 ('quiet', 0.9822649955749512),
 ('seeing', 0.9818342328071594)]

In [ ]:
model.wv.similarity('arya','sansa')

0.98124

In [ ]:
model.wv['god'].shape

(100,)

In [ ]:
vec = model.wv.get_normed_vectors()

In [ ]:
vec

array([[ 0.06104444,  0.00805089,  0.14057022, ...,  0.07629986,
        -0.05664488,  0.15909192],
       [ 0.13909657,  0.13039207,  0.10476737, ...,  0.039958  ,
        -0.05561822,  0.01832185],
       [ 0.01324508, -0.00532298, -0.15991656, ..., -0.14982995,
         0.04752188, -0.07303192],
       ...,
       [ 0.10724463,  0.07111684,  0.07036176, ..., -0.05874126,
         0.02739407, -0.00438259],
       [ 0.07510372,  0.03507764,  0.03953507, ..., -0.04961501,
         0.01211071, -0.01364081],
       [ 0.07001054,  0.06346483,  0.04181454, ..., -0.0657134 ,
         0.04124255, -0.08080773]], dtype=float32)

In [ ]:
model.wv.get_normed_vectors().shape

(8577, 100)

In [ ]:
y = model.wv.index_to_key

In [ ]:
len(y)

8577

In [ ]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'her',
 'was',
 'she',
 'you',
 'had',
 'that',
 'in',
 'it',
 'as',
 'with',
 'not',
 'him',
 'for',
 'but',
 'is',
 'have',
 'lord',
 'at',
 'be',
 'my',
 'on',
 'they',
 'no',
 'ser',
 'said',
 'would',
 'me',
 'them',
 'one',
 'from',
 'your',
 'will',
 'when',
 'were',
 'if',
 'all',
 'so',
 'their',
 'are',
 'man',
 'could',
 'been',
 'we',
 'did',
 'there',
 'by',
 'what',
 'this',
 'do',
 'up',
 'more',
 'lady',
 'who',
 'king',
 'jaime',
 'some',
 'only',
 'men',
 'than',
 'well',
 'down',
 'father',
 'or',
 'out',
 'has',
 'back',
 'too',
 'old',
 'cersei',
 'made',
 'told',
 'hand',
 'queen',
 'know',
 'never',
 'an',
 'like',
 'thought',
 'little',
 'even',
 'before',
 'brienne',
 'time',
 'though',
 'where',
 'can',
 'how',
 'us',
 'about',
 'eyes',
 'still',
 'must',
 'might',
 'off',
 'see',
 'black',
 'good',
 'once',
 'come',
 'red',
 'son',
 'into',
 'here',
 'sam',
 'boy',
 'brother',
 'long',
 'way',
 'should',
 'face',


In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=10)

In [ ]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [ ]:
X

array([[ 0.367952  ,  0.19412833,  0.02961352, ...,  0.00220476,
        -0.08814873,  0.15984052],
       [ 0.45913324,  0.07729203, -0.06406809, ..., -0.11406123,
         0.03015064,  0.01096125],
       [-0.42120814,  0.07522351, -0.17062023, ..., -0.0963426 ,
         0.11686712,  0.09936098],
       ...,
       [-0.00707908, -0.04515404, -0.04426622, ..., -0.07305823,
        -0.04283581,  0.003177  ],
       [-0.03356098, -0.05534774,  0.09731588, ..., -0.05343731,
        -0.0311762 ,  0.04304401],
       [-0.11642158, -0.08949614,  0.04209061, ..., -0.03436643,
        -0.00714685,  0.02102357]], dtype=float32)

In [ ]:
X.shape

(8577, 10)

In [ ]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()